choco install angryip
choco install audacity
choco install audacity-lame
choco install autohotkey
choco install google-backup-and-sync
choco install sqlitebrowser
choco install putty
choco install gpmdp
choco install lastpass
choco install lastpass-for-applications
choco install paint.net
choco install putty.install
choco install teracopy
choco install toggl
choco install rdmfree
choco install windirstat
choco install winmerge
choco install sysinternals
choco install rufus